---
- name: Auxiliary Tools
  hosts: offloader
  tags:
    - tmux
    - speedtest
  roles:
    - tools-install

- name: Install Docker Stuff
  hosts: offloader
  tags:
    - docker
  roles:
    - docker-install

- name: install and configure batman
  hosts: offloader
  tags:
    - bat
    - batman
    - batman5
    - batmanv5
    - batman_v5
  roles:
    - batman-install

- name: install and configure fastd
  hosts: offloader
  tags:
    - fastd
  roles:
    - fastd-install
  
- name: install and configure respondd
  hosts: offloader
  tags:
    - respondd
  roles:
    - respondd-install
  vars:
    router_name: "bodensee-uboot"
    respondd_wan: "{{ outbound_lan_interface }}"

- name: install and configure wifi AP
  hosts: offloader
  tags:
    - wifi
    - wlan
    - hostapd
  roles:
    - wifi-ap
  vars:
    hostapd_bridge: "br-ffbsee"

- name: install and activate kdump
  hosts: offloader
  tags:
    - kdump
    - crashdump
    - coredump
    - dump
  roles:
    - kdump
  #tasks:
    # configure raspberry pi kernel
    # DEFAULT RASBIAN PI KERNEL DOES NOT SUPPORT THIS
    #- name: configure kdump reserved RAM on the raspberry pi
    #  become: yes
    #  replace:
    #    path: /boot/cmdline.txt
    #    regexp: '((?s)^((?!crashkernel={{ kdump_crashkernel_mem }}).)*)\n$'
    #    replace: '\1 crashkernel={{ kdump_crashkernel_mem }}\n'
    #  when:
    #    - (ansible_distribution | lower) == 'debian'
