---
- name: install and configure batman
  hosts: offloader
  roles:
    - batman-install

- name: install and configure fastd
  hosts: offloader
  roles:
    - fastd-install
  
- name: install and configure respondd
  hosts: offloader
  roles:
    - respondd-install
