---
- name: Auxiliary Tools
  hosts: offloader
  tags:
    - tmux
    - speedtest
  roles:
    - tools-install

- name: Install Docker Stuff
  hosts: offloader
  tags:
    - docker
  roles:
    - docker-install
#TODO make sure /etc/network/interfaces only holds the dource-dir entry
- name: install and configure batman
  hosts: offloader
  tags:
    - bat
    - batman
    - batman5
    - batmanv5
    - batman_v5
  roles:
    - batman-install

- name: install and configure fastd
  hosts: offloader
  tags:
    - fastd
  roles:
    - fastd-install
  
- name: install and configure respondd
  hosts: offloader
  tags:
    - respondd
  roles:
    - respondd-install

- name: fix dhcp client issues
  hosts: offloader
  tags:
    - dhcp
  roles:
    - dhcpcd
  vars:
    dhcpcd_global_config:
      - keyword: noipv4ll
      - keyword: nogateway
        state: absent
      - keyword: denyinterfaces
        value: "bat* vlan*"
      - keyword: clientid
      - keyword: duid
        state: absent
      - keyword: slaac
        value: hwaddr
    dhcpcd_interface_config:
      - name: "{{ outbound_lan_interface }}"
        config: |
          "gateway"
          "metric 0"
      - name: "br-welt"
      - name: "br-ffbsee"


- name: install and configure wifi AP
  hosts: offloader_not
  tags:
    - wifi
    - wlan
    - hostapd
  roles:
    - wifi-ap

- name: install alfred-scripts for ffbsee
  hosts: offloader
  tags:
    - alfred
    - printmap
    - print-map
  roles:
    - alfred-install

- name: install and activate kdump
  hosts: offloader
  tags:
    - kdump
    - crashdump
    - coredump
    - dump
  roles:
    - kdump
  #tasks:
    # configure raspberry pi kernel
    # DEFAULT RASBIAN PI KERNEL DOES NOT SUPPORT THIS
    #- name: configure kdump reserved RAM on the raspberry pi
    #  become: yes
    #  replace:
    #    path: /boot/cmdline.txt
    #    regexp: '((?s)^((?!crashkernel={{ kdump_crashkernel_mem }}).)*)\n$'
    #    replace: '\1 crashkernel={{ kdump_crashkernel_mem }}\n'
    #  when:
    #    - (ansible_distribution | lower) == 'debian'

- name: run unify docker container
  hosts: offloader_crash
  tags:
    - docker
    - unify
    - unifi
  tasks:
    - command: "docker run --init -d --restart always --net=host -e TZ='Europe/Berlin' -v ~/unifi:/unifi --name unifi jacobalberty/unifi:latest"
    #on arm :arm32v7
