---
- name: Install additional tools
  become: yes
  apt:
    update_cache: yes
    pkg:
      - aptitude
      - fsarchiver
      - iftop
      - nano
      - nmap
      - net-tools
      - speedtest-cli
      - tmux
      - traceroute
      - vlan
      - git
      - bc
    state: present
