inbound_lan_interface: "eth0"
outbound_lan_interface: "eth0"

router_hardware: "Raspberry Pi 4B"
router_contact: "alex@toolbox"
respondd_wan: "{{ outbound_lan_interface }}"

alfred_maplevel: all
alfred_community: Bodensee
alfred_router_latitude: 47.596924886
alfred_router_longitude: 9.543090463
alfred_router_version: 2.2.2
alfred_router_contact: alex@toolbox
alfred_router_autoupdater_enabled: false
alfred_router_autoupdater_branch: none