---
- name: Install fastd
  become: yes
  apt:
    update_cache: yes
    name: fastd
    state: present

- name: Create fastd directory
  become: yes
  file:
    path: '/etc/fastd'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'

- name: Check that there is no fastd key
  become: yes
  stat:
    path: /etc/fastd/secret_key.txt
  register: stat_result

- name: Generate fastd secret key
  shell: 'fastd --generate-key --machine-readable'
  register: registered_fastd_secret
  when: fastd_secret_key == '' and stat_result.stat.exists == False
  check_mode: no

- name: Read secret key
  become: yes
  shell: 'cat /etc/fastd/secret_key.txt'
  register: registered_fastd_secret
  check_mode: no
  when: fastd_secret_key == '' and stat_result.stat.exists == True

- name: Set fastd secret key
  set_fact:
    fastd_secret_key: "{{ registered_fastd_secret.stdout | trim }}"
  when: fastd_secret_key == ''

- name: Put secret key to host
  become: yes
  template:
    src: 'templates/secret_key.j2'
    dest: '/etc/fastd/secret_key.txt'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=,o='

- name: Create fastd welt directory
  become: yes
  file:
    path: '/etc/fastd/welt'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'

- name: Create welt config
  become: yes
  template:
    src: 'templates/ffmuc-welt.j2'
    dest: '/etc/fastd/welt/fastd.conf'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=,o='

- name: Create fastd ffbsee directory
  become: yes
  file:
    path: '/etc/fastd/ffbsee'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'

- name: Create ffbsee config
  become: yes
  template:
    src: 'templates/ffbsee.j2'
    dest: '/etc/fastd/ffbsee/fastd.conf'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=,o='

- name: Enable and start fastd welt
  become: yes
  systemd:
    name: fastd@welt
    state: started
    enabled: yes

- name: Enable and start fastd ffbsee
  become: yes
  systemd:
    name: fastd@ffbsee
    state: started
    enabled: yes
